products = ['Sankofa Foods', 'James Town Coffee', 'Bioko chocolate', 'Blue Skies Ice Cream', 'Fair Afric Chocolate',
            'Kawa Moka Coffee', 'Aphro spirit', 'Mensado Bisap', 'Voltic' ]

prices = [30, 25, 40, 20, 20, 35, 45, 50, 35]

last_week = [2, 3, 5, 8, 4, 4, 6, 2, 9]


# the total average price of all products
# number = 0
# sum = 0
#
# for amount in prices:
#     sum += amount
#     number += 1
# print(sum)
# print(number)



# New price list that reduces the old price by $5
reduced_price = []
for price in prices:
    new_price = price - 5
    reduced_price.append(new_price)
print(reduced_price)



# total revenue generated by the product
# total_revenue = 0
# for p,l in zip(prices, last_week):
#      total_revenue += p*l
# print(total_revenue)


# the average daily revenue generated from the products
# total_revenue = 0
# for p,l in zip(prices, last_week):
#      total_revenue += p*l
#
# average = total_revenue / len(last_week)
# print(round(average))


# which rices are less than 30 in nw prices
np_list = []
for np in reduced_price:
    if np < 30:
        np_list.append(np)
print(np_list)
